Vidly/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class CustomerController : Controller
    {
        private ApplicationDbContext _context;

        public CustomerController()
        {
            _context = new ApplicationDbContext();
        }
    
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }


        // GET: Customer
        public ActionResult Index()
        {
            return View(new CustomersViewModels()
            {
                Customers = _context.Customers.Include("MembershipType").ToList()
            });
        }

        public ActionResult Details(int id)
        {
            var customer = _context.Customers.Include("MembershipType").FirstOrDefault(c => c.Id == id);
            if (customer != null)
            {
                return View(customer);
            }
            else
            {
                return HttpNotFound();
            }
        }

        public ActionResult New()
        {
            return View("CustomerForm", new CustomerFormViewModel()
            {
                MembershipTypes = _context.MembershipTypes.ToList(),
                Customer = new Customer()
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(CustomerFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("CustomerForm", new CustomerFormViewModel()
                {
                    Customer = viewModel.Customer,
                    MembershipTypes = _context.MembershipTypes.ToList()
                });
            }


            if (viewModel.Customer.Id == 0)
            {
                // new customer
                _context.Customers.Add(viewModel.Customer);
            }
            else
            {
                var customerInDb = _context.Customers.Single(c => c.Id == viewModel.Customer.Id);
                customerInDb.IsSubscribedToNewsletter = viewModel.Customer.IsSubscribedToNewsletter;
                customerInDb.BirthDate = viewModel.Customer.BirthDate;
                customerInDb.MembershipTypeId = viewModel.Customer.MembershipTypeId;
                customerInDb.Name = viewModel.Customer.Name;

            }
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var customer = _context.Customers.Include("MembershipType").FirstOrDefault(c => c.Id == id);
            if (customer != null)
            {
                return View("CustomerForm", new CustomerFormViewModel()
                {
                    Customer = customer,
                    MembershipTypes = _context.MembershipTypes.ToList()
                });
            }
            else
            {
                return HttpNotFound();
            }
        }
    }
}

Vidly/Controllers/RentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.DTOs;
using Vidly.Models;
using Vidly.ViewModels;

namespace Vidly.Controllers
{
    public class RentalsController : Controller
    {
        private ApplicationDbContext _context;

        public RentalsController()
        {
            _context = new ApplicationDbContext();
        }

        // GET: Rentals
        public ActionResult New()
        {
            return View();
        }

        // GET: Returns
        public ActionResult Returns(int id = -1)
        {
            var initCustomer = _context.Customers.SingleOrDefault(c => c.Id == id);
            if (initCustomer != null)
            {
                return View(new ReturnsViewModel()
                {
                    HasInitCustomer = id >= 0,
                    InitCustomer = AutoMapper.Mapper.Map<Customer, CustomerDto>(initCustomer)
                });
            }
            else
            return View(new ReturnsViewModel() { HasInitCustomer = false });
        }
    }
}

Vidly/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_NavBar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Vidly</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Vidly/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
    <a class="navbar-brand" href="#">Vidly</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">@Html.ActionLink("Movies", "Index", "Movies", new object { }, new { @class = "nav-link" })</li>
            <li class="nav-item">@Html.ActionLink("Customers", "Index", "Customer", new object { }, new { @class = "nav-link" })</li>
            <li class="nav-item">@Html.ActionLink("New Rental", "New", "Rentals", new object { }, new { @class = "nav-link" })</li>
            <li class="nav-item">@Html.ActionLink("Returns", "Returns", "Rentals", new object { }, new { @class = "nav-link" })</li>

        </ul>
        @Html.Partial("_LoginPartial")
    </div>
</nav>